name: CI orchestrator

on:
  pull_request:
    branches:
      - main

jobs:
  #
  # License and Markdown Check
  #
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v11

  #
  # Detect changes to start relevant workflows
  #
  changes:
    uses: ./.github/workflows/detect-changes.yml

  render_c4model_dh_base_model:
    needs: changes
    if: ${{ needs.changes.outputs.render_c4model_dh_base_model == 'true' }}
    uses: Energinet-DataHub/.github/.github/workflows/structurizr-render-diagrams.yml@v11
    with:
      structurizr_workspace_filename: dh-base-model
    secrets:
      pat_token_retrigger_workflow: ${{ secrets.pat_token_repo_workflow }}

  #
  # Branch policy status check
  #

  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs: [ci_base, render_c4model_dh_base_model]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
