name: CI orchestrator

on:
  pull_request:
    branches:
      - main

jobs:
  #
  # License and Markdown Check
  #
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v10

  #
  # Detect changes to start relevant workflows
  #
  changes:
    uses: ./.github/workflows/detect-changes.yml

  render_diagrams:
    needs: changes
    if: ${{ needs.changes.outputs.render_diagrams == 'true' }}
    uses: ./.github/workflows/render-diagrams.yml

  diagrams_added:
    needs: changes
    if: ${{ needs.changes.outputs.diagrams_added == 'true' }}
    uses: ./.github/workflows/diagrams-added.yml

  #
  # Branch policy status check
  #

  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs: [ci_base, render_diagrams, diagrams_added]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
