name: Detect changes

# DESCRIPTION:
# This workflow will determine which categories of jobs should be executed,
# based on detected changes.
# It should be used by the 'ci-orchestrator.yml'.

on:
  workflow_call:
    outputs:
      render_diagrams:
        value: ${{ jobs.changes.outputs.render_diagrams }}

jobs:
  changes:
    name: Determine relevant jobs
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      render_diagrams: ${{ steps.filter.outputs.render_diagrams }}
    steps:
      # For pull requests it's not necessary to checkout the code because GitHub REST API is used to determine changes
      - name: Checkout repository
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3

      - name: Detect file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            render_diagrams:
              - 'source/**'
              - '.github/workflows/render-diagrams.yml'
              - '.github/workflows/detect-changes.yml'
