name: Detect changes

# DESCRIPTION:
# This workflow will determine which categories of jobs should be executed,
# based on detected changes.
# It should be used by the 'ci-orchestrator.yml'.

on:
  workflow_call:
    outputs:
      render_c4model_dh_base_model:
        value: ${{ jobs.changes.outputs.render_c4model_dh_base_model }}

jobs:
  changes:
    name: Determine relevant jobs
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      render_c4model_dh_base_model: ${{ steps.filter.outputs.render_c4model_dh_base_model }}
    steps:
      # For pull requests it's not necessary to checkout the code because GitHub REST API is used to determine changes
      - name: Checkout repository
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3

      - name: Detect file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            render_c4model_dh_base_model:
              - 'docs/diagrams/c4-model/dh-base-model.dsl'
              - 'docs/diagrams/c4-model/dh-base-model.json'
