name: Render C4 models with structurizr

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  render-c4:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
      
    uses: Energinet-DataHub/.github/.github/workflows/structurizr.yml@V10
    with:
      dsl: 'source/datahub3-model/model.dsl'