name: Render C4 models with Structurizr

on:
  workflow_call: {}

jobs:
  render_c4:
    uses: Energinet-DataHub/.github/.github/workflows/structurizr.yml@v10
    with:
      dsl: source/datahub3-model/model.dsl source/datahub3-model/examples/migration.dsl source/datahub3-model/examples/wholesale.dsl
    secrets: inherit
