name: Render C4 models with Structurizr

on:
  workflow_call: {}

jobs:
  render-c4:
    uses: Energinet-DataHub/.github/.github/workflows/structurizr.yml@djorgensen/supoort-structurizr-workflow
    with:
      dsl: "source/datahub3-model/model.dsl"
    secrets: inherit
