name: Render C4 models with Structurizr

on:
  workflow_call: {}

jobs:
  render_c4:
    uses: Energinet-DataHub/.github/.github/workflows/structurizr.yml@v11
    with:
      dsl: docs/diagrams/c4-model/model.dsl,source/datahub3-model/future-model.dsl
    secrets: inherit
